# Generated by Django 3.1.5 on 2021-01-18 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20210115_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='mixer',
            name='shower',
            field=models.BooleanField(default=False, verbose_name='Наличие душа'),
        ),
        migrations.AddField(
            model_name='mixer',
            name='type_shower',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Тип душа'),
        ),
    ]
