# Generated by Django 3.1.5 on 2021-01-27 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20210127_1406'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Baths',
            new_name='Bath',
        ),
        migrations.AlterModelOptions(
            name='bath',
            options={},
        ),
        migrations.AlterModelTable(
            name='bath',
            table=None,
        ),
    ]
